### PR TITLE
Add support for local development

### PR DESCRIPTION
**Pull request by TPRobots**
Pull request opened by github-pullrequestcreator.

### CODE REVIEW

**Comment by thomicdk** [comment]
I really like the idea of making it easy to test Skift while developing. I have been thinking during the weekend, and I have a suggestion, which is inspired by how the [VueJS repository](https://github.com/vuejs/vue) is structured:

Rename the folder `local-serve` to `examples`. I think it's a more "friendly" name for people coming from the outside.

The structure of examples should be:
```
/examples
    /basic
        index.html        (this is the HTML file from this PR)
    /configure-tracking
        index.html
    /configure-condition
        index.html
    readme.md
```
(The two configure examples and the readme.md can be added later)

Also, move `serve.js` to `/config` and make it serve the `/examples` (and `/dist`) folder.

What do you think ?

**Comment by MartinMouritzen** [comment]
I think that sounds good. I will alter the structure :)

**Comment by halfzebra** [comment]
@MartinMouritzen have you tried `npm test`?

If yes, what went wrong?

**Comment by MartinMouritzen** [comment]
Hi @halfzebra 
Hmm, that actually seems to fit the same purpose as what I wanted. - I don't know if my PR is relevant then :)
I expected npm test to "just" run some unit tests, maybe run it on npm start as well?

**Comment by halfzebra** [comment]
@MartinMouritzen your PR is super-relevant to #28 🙂 

Testing setup is somewhat limited, so there's a perfect use case for your stuff!

**Comment by halfzebra** [comment]
@MartinMouritzen Thanks for the PR 👍 

I'll merge it and take it from here.

**Pull request merged**
